version: "3.9"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 9000:80
        volumes:
            - ./src:/var/www/html
    db:
        image: mariadb:10.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: root
        volumes:
            - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 3303:3303
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        restart: always
        ports:
            - 6006:80
        environment:
            - PMA_ARBITRARY=1
